### ISSUE TITLE
Selecting English as language on Studo.linto.app does not list any services , only french does.

### ISSUE THREAD

**Issue by jkfnc** [linto-ai/linto-studio#115]

**Comment by damienlaine** [comment]
Greetings,

Thank you for reaching out. I'd like to inform you that in this beta version, we have not yet deployed transcription services for English. However, English language is fully supported. As for your request, we'll make it available by the end of this week.

Please keep an eye out for updates. I will promptly close this issue once the English service is deployed.

Currently, LinTO Studio only offers support for both French and English due to the automated timestamp alignment (when correcting text), that is language dependent.

Best regards,
